spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:13306/ps?serverTimezone=UTC&characterEncoding=UTF-8
    username: local
    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
        jdbc:
          time_zone: Asia/Seoul
  jdbc:
    template:
      batch-size: 100
  kafka:
    bootstrap-servers: [ "localhost:19094" ]
    group-id: "settlements_1"
    schema-registry-url: "http://localhost:8085"
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
common:
  response:
    stack-trace: true
