spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ps?serverTimezone=UTC&characterEncoding=UTF-8
    username: local
    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
pg:
  toss:
    base-url: https://api.tosspayments.com/v1/
    secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6